### ISSUE TITLE
Add This line of Code on FeedsFragment

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Devs-Portfolio-App#100]
@emmaunel  please add this line of code on your Add Feeds Fragment to help with the Naming changes on the ToolBar. I noticed once you click it keeps changing from the Dev Name to projects or Interest 

`  ((AppCompatActivity)(context)).getSupportActionBar().setTitle(getString(R.string.Feeds));`

**Comment by emmaunel** [comment]
ok

**Comment by Madonahs** [comment]
@emmaunel  solved the problem, i will push it to our branch.
