### ISSUE TITLE
Nav Drawer Font | check Help And Log out button they blink the same time.

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Devs-Portfolio-App#59]
I have noticed once you click on the any the font changes to default , also noticed once you click on the Help and Log out they blink on the same time :) to be worked on .

**Comment by Madonahs** [comment]
@CleverChuk  Noticed this, when you get time check it out.

**Comment by Madonahs** [comment]
Looks like the only options we have is to try in built fonts. Then replace all fonts declarations :) Lol!

**Comment by CleverChuk** [comment]
We can get around that by setting theme on root view for all xml files excluding the one for Nav drawer

**Comment by Madonahs** [comment]
Okay, I can work on this today :) Thanks.

**Comment by Madonahs** [comment]
@CleverChuk  tried doesnt seem to clean the bug, we can discuss it when you get ime.

**Comment by CleverChuk** [comment]
I am re-evaluating that fix.

**Comment by Madonahs** [comment]
Thanks. 😊
