### ISSUE TITLE
User Theme - Manager

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Devs-Portfolio-App#60]
_Hello New Team, I think Add Theme Manager might be a complex task, we should all help Emmanuel :) So any ideas are welcome. We can discuss this on the Hangout before we start._

**Comment by MaherSoua** [comment]
Ok for me

**Comment by Madonahs** [comment]
@MaherSoua  did you start this already? i created a settings Activity

**Comment by MaherSoua** [comment]
@Madonahs , not yet I will use your settings activity

**Comment by CleverChuk** [comment]
Which branch is this on?

**Comment by Madonahs** [comment]
@CleverChuk I wanted this to go setting, didn't open a branch for it yet you can open one called Nav-functions.

**Comment by Madonahs** [comment]
@MaherSoua  👍

**Comment by Madonahs** [comment]
Dark theme Done!
