### ISSUE TITLE
Feeds Activity Class FeedImplementation Branch

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Devs-Portfolio-App#73]
The Floating button should already lead to FeedsActivity :) So you are good to go.

**Comment by emmaunel** [comment]
Thanks

**Comment by Madonahs** [comment]
@HemantNimje  should help you with the link he showed us :)

**Comment by Madonahs** [comment]
You can look at some of the links shared: 
@HemantNimje  can help here too.

[Sample Feed](https://portfolium.com/entry/bluetooth-messenger)
[Sample 2 ](http://cdn.marketplaceimages.windowsphone.com/v8/images/fb71f5a4-93d6-498a-82cb-47688df4de9c?imageType=ws_screenshot_max&rotation=0)

**Comment by HemantNimje** [comment]
Thanks @Madonahs

**Comment by Madonahs** [comment]
@HemantNimje  Here work with @emmaunel  on this :) you can help him with the layout 👍

**Comment by HemantNimje** [comment]
Sure.

**Comment by emmaunel** [comment]
Everything is under control now. We don't need this issue anymore. @Madonahs
