### ISSUE TITLE
Navigation Drawer Functionalities | Nav-Drawer Branch

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Devs-Portfolio-App#81]
# Brief
Feel free to join me on implementing the Navigation Drawer Functions.  On the Navigation Drawer we have the following;

- User Name 

- Profession 

- Message

- Manage Profile

- About

- Settings

- Help

- Log Out

## Navigation Drawer
So the Navigation drawer will help users navigate our App.

## Features

**_Messages **.** Manage Profile **.** About **.** Settings **.** Help **.** Log out ._** 
I already included Notification on the settings, so no need to do it as a stand alone. So on messages users should be able to text other users, Manage profile will help users navigate to parts where they want to advance on their apps, About this will be a small description about Authors and the idea behind the App. 

## Settings

Setting will include several features; 

- General : this has Enable social recommendations **.** Display name **.** Add friends to messages

- Notifications : this has new message notifications **.** Ringtone **.** Vibrate

- Data & sync : this has Sync frequency **.** system sync settings

- Theme : this is where we allow users to set a theme for their entire app. 

## Mock Up
![navigation drawer](https://user-images.githubusercontent.com/11560987/36948265-c19834f2-1f9d-11e8-8268-b85534aabee7.png)

**Comment by Madonahs** [comment]
Almost Done.

**Comment by SrChip15** [comment]
Great! 👍
