### ISSUE TITLE
Data Transfer between Fragments

### ISSUE THREAD

**Issue by emmaunel** [Madonahs/Devs-Portfolio-App#84]
So I made a fragment for adding items to the Feeds fragment. But as I was trying to pass a string to the feeds fragment, the app crashes. So can anyone help with passing data between those two fragments?

**Comment by Madonahs** [comment]
You can share your error , would love to look at it. 👍

**Comment by emmaunel** [comment]
I push my changes to FeedsImplementation, you can run it and see the error

**Comment by Madonahs** [comment]
@emmaunel  thanks let me pull them.

**Comment by Madonahs** [comment]
@emmaunel  I see this the error you are getting the null object reference .

` on a null object reference. `

**Comment by emmaunel** [comment]
Yeah but the problem. It is not actually null

**Comment by Madonahs** [comment]
On the detach method I see you declared it null.

**Comment by Madonahs** [comment]
@emmaunel  Sorry i have seen. Lol,

**Comment by Madonahs** [comment]
@emmaunel just noticed interaction  is not initialized and is hence throwing a null pointer exception when you use it to reference the receive function. I was reading this https://developer.android.com/training/basics/fragments/communicating.html#Implement

**Comment by emmaunel** [comment]
So I am progressing but I just have one more problem. 
When the apps first run, it loads up feedsfragment but the problem that same fragment gets data from the addFeeds activity. So when it loads addFeeds sents null to the feedsfragment.
What I need help is how to ignore the data from addFeeds activity at the launch of the app but after that, can then receive data from it

**Comment by emmaunel** [comment]
Update: I kind of fix the null pointer

**Comment by Madonahs** [comment]
@emmaunel  awesome, good news 👍 you can push and i will look at it.

**Comment by emmaunel** [comment]
yes please. my heads hurts from this.

**Comment by emmaunel** [comment]
@Madonahs check it out

**Comment by Madonahs** [comment]
@Emmanuel thanks. 😊 will keep you updated. 😎

**Comment by Madonahs** [comment]
@emmaunel  Going through it can you try receiving the bundle into a Bundle object using getArguments method and check it against null.

**Comment by Madonahs** [comment]
I see you did that 👍

**Comment by Madonahs** [comment]
@emmaunel  some recommendation 

- Lets remove unused method, activities can layouts.

- Make sure you remove them on Manifest too. 

- Looks like error might be something small. Process looks good but too many unused.

**Comment by emmaunel** [comment]
@Madonahs ok
