### ISSUE TITLE
Create Forgot Password

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Devs-Portfolio-App#85]
**We need to let users create a new password if they forget their password. @MaherSoua**

**Comment by MaherSoua** [comment]
You have just to call resetPassword from AppLoginManager and pass context (activity) and email as params

in the activity you will find onResetPasswordSuccess and onResetPasswordFailed methods , you can add action according to your status( e.g Toast)


AppLoginManager .resetPassword(this, "test@test.com")
