### ISSUE TITLE
Login Activity Bug

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Devs-Portfolio-App#96]
See Image : below. 
![screenshot_20180309-140623](https://user-images.githubusercontent.com/11560987/37227816-21691d56-23a4-11e8-9771-0646a36fbc74.png)

**Comment by emmaunel** [comment]
@Madonahs what branch is this bug in?

**Comment by Madonahs** [comment]
Noticed it on Master. I have been working on Feeds. Once done i will send some changes 👍

**Comment by MaherSoua** [comment]
@Madonahs I think that develop branch is up to date try to merge it with master, may be it should resolve the problem.

**Comment by Madonahs** [comment]
@MaherSoua  you are right it was fixed early, need to close it. Been working on feeds.
